export const APP_FONTS = {
  FONT_BOLD: `HelveticaNeue-Bold`,
  FONT_MEDIUM: `HelveticaNeue-Medium`,
  FONT_REGULAR: `Helvetica Neue`,
  FONT_SEMIBOLD: `HelveticaNeue-Medium`,
  FONT_LIGHT: `Helvetica-Light`
};

export const APP_THEME = {
  APP_TAB_ICON_COLOR_DESELECTED: '#4D4D4D',
  APP_TAB_ICON_COLOR_SELECTED: '#BE2727',
  APP_BASE_COLOR: '#BE2727',
  APP_BASE_COLOR_LIGHT: '#7ECEAA',
  APP_BASE_COLOR_DARK: '#01674E',
  APP_BASE_FONT_COLOR: '#FFF',
  APP_FONT_COLOR_DARK: '#122632',
  APP_FONT_COLOR_REGULAR: '#000',
  APP_BACKGROUND_COLOR: '#F8F8F8',
  APP_LIST_BORDER_COLOR: '#D1D2D4',
  APP_LIST_FONT_COLOR: '#86898E',
  APP_SIDEBAR_SEPERATER_COLOR: '#D8ECE3',
  APP_STEPPER_BUTTON_COLOR: 'rgba(18, 38, 50, 0.5)',
  APP_BASE_COLOR_OFFWHITE: '#F2F2F2',
  APP_BASE_COLOR_WHITE: '#ffffff',
  APP_BASE_COLOR_GREY: '#D3D4D6',
  APP_BASE_COLOR_LIGHT_GREY: '#aaa',
  APP_BASE_COLOR_DARK_GREY: '#8A8D92',
  APP_BASE_COLOR_TRANSPARENT: 'rgba(0, 0, 0, 0)',
  APP_COLOR_DARK_BLACK: '#000',
  APP_FONT_COLOR_ORANGE: '#F6BF70',
  APP_FONT_COLOR_RED: '#ff0000',
  APP_LIGHT_COLOR_GREY: 'rgba(212,212,212,1)'
};

export const APP_ROUTE = {
  DASHBOARD: 'Dashboard'
};
